### ISSUE TITLE
ukol.py

### ISSUE THREAD

**Issue by AlenaNobi** [AlenaNobi/Kurz_Python#1]
@KristynaSodomkova Podívej se mi prosím na úkol

**Comment by KristynaSodomkova** [comment]
Ahoj, prosim oprav: 
`@abstractmethod
def calculate_tax(self):
    pass

@abstractmethod
def __str__(self):
    pass`

- chybi tam self a to by pak nemuselo pravcovat spravne
- calculate_tax nemusi byt oznaceno jako @property, ale normalni metoda, cili odstranis ten dekorator @property a pak na dalsich mistech, kde tu metodu volas uz budes pouzivat `calculate_tax()`
- pozor na pojmenovani promenne list, protoze to pak prebiji pythonovsky typ list, radeji pojmenuj treba properties_list - to by bylo dobre nadhodit k diskuzi na lekci nebo v BR
- v class Residence mas commercial definovane jako dva stringy, lepe je tam dat True or False, takze pak muzes pouzit `if self.commercial` namisto `if self.commercial == "commercial"` a potom pri volani to muze vypadat takto: 
`kancelar1 = Residence(brno, 90, commercial=True)`
- uprav metodu `__str__` ve tride Residence:
- napr. takhle: 
`def __str__(self):
        property_type = "Komerční nemovitost" if self.commercial else "Bytová nemovitost"
        return f"{property_type} v lokalitě {self.locality.name} ({self.locality.locality_coefficient}), {self.area} m², daň: {self.calculate_tax()} Kč."
`
- v calculate_tax metode u tridy Residence mas for loop na vypocet dane, spis pouzij primy vpocet dane:
- napr: `tax = math.ceil(self.area * self.locality.locality_coefficient * 15)` a pridej podminku na self.commercial

**Comment by KristynaSodomkova** [comment]
Je videt, ze jsi ukol vypracovala sama a k tomu moc gratuluji!
Prace je dobra, takze u me mas splneno, jen si prosim oprav ty upravy, ktere jsem tady napsala
Velmi dobre chapes dedicnost, takze klobouk dolu, to jsi pouzila spravne.
Mit pripominky ke kodu je uplne normalni, je to bezna soucast programatorovi prace, tak to prosim ber jako moznost se neco priucit, nikoliv kritiku
Celkove tedy parada, jen tak dal :)

**Comment by AlenaNobi** [comment]
@KristynaSodomkova Ahoj, díky moc za čas a hlavně za připomínky ke kódu! Upravila jsem jej, tak případně ještě koukni :)

**Comment by KristynaSodomkova** [comment]
Ahoj Aleno, super, gratuluji a uzaviram issue :)
